Made the program easier to use for people without computer experience
parthsarin/RandomSpotifySong pull request #1
Opened 2021-02-18 08:33 UTC by HoboJoe2

Hi,
I understand if you don't want to merge this request, because I have changed a lot about the program.
I wanted to make it easier for people who don't know anything about programming to use, so I made it so that the program runs from a batch file and has interactive inputs instead of command line arguments.
I also made it so that the program is in verbose mode always.
Thank you for making such an awesome program, I've been listening to random songs while coding this ^_^

2021-02-19 08:41 UTC, parthsarin commented on README.md
> +To run the program, double click on `RandomSpotifySong.bat`. There is also a shortcut file which can be moved from the original folder and runs the same as `RandomSpotifySong.bat`.
This is great! `.bat` only work in DOS-based OS systems. Could you add instructions for non-DOS systems for executing the Python file directly?

2021-02-19 08:42 UTC, parthsarin commented on README.md
> -You can also do the same thing by executing the following command:
I think it'd be useful to keep some instructions about running the file with the `python` executable just to keep it OS-independent. Thoughts?

2021-02-19 08:42 UTC, parthsarin commented on RandomSpotifySong.bat
> +python -m venv .env && cd .env/Scripts && activate && cd .. && cd .. && pip install -r requirements.txt && python randomsong.py
Hahaha, nice.

2021-02-19 08:45 UTC, parthsarin commented on randomsong.py
> +	os.system("cls")
Oh this makes the output so much nicer! Could you make this system independent also? The command for linux and bash is `clear` and you should be able to use `os.name` to determine which command to use.

2021-02-19 08:48 UTC, parthsarin requested changes
I love what you've done with this! Using verbose mode, clearing the terminal output, etc. are all fantastic changes! Could you make a few of your changes platform independent (see my comments)? Also, could you remove the `Shortcut.lnk` file if it's not necessary?

I appreciate your attention; this should definitely make it easier for non-programmers to use!

2021-02-21 05:57 UTC, HoboJoe2 commented
Ok, I just pushed the commits to my fork, I'm pretty sure they should show up. This is my first time contributing to a project and using pull requests so I'm still learning.
I don't know much about operating systems other than windows so thanks for the hints about how to make it works on other operating systems.
Thanks for the great feedback, like I said this is my first time contributing to an opensource project and you have been really nice :)

2021-02-23 06:54 UTC, merged

2021-02-23 06:54 UTC, parthsarin commented
It looks great, @HoboJoe2! Thanks for helping contribute!